// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDHYOgTeifdzwv1TDBcD6AlVh5UhVr-t8',
    appId: '1:581478733162:web:d8faaafa46015a94738113',
    messagingSenderId: '581478733162',
    projectId: 'shoe-shop-c265f',
    authDomain: 'shoe-shop-c265f.firebaseapp.com',
    storageBucket: 'shoe-shop-c265f.firebasestorage.app',
    measurementId: 'G-EE62DLWGR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxct6cY0zpKLc89cJrz64q9Pk3nkz9Nl4',
    appId: '1:581478733162:android:98f5f422214bd873738113',
    messagingSenderId: '581478733162',
    projectId: 'shoe-shop-c265f',
    storageBucket: 'shoe-shop-c265f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQGheLE7B6UF3kcaOf161a7e3TpfUHYnE',
    appId: '1:581478733162:ios:23177416afcb72d3738113',
    messagingSenderId: '581478733162',
    projectId: 'shoe-shop-c265f',
    storageBucket: 'shoe-shop-c265f.firebasestorage.app',
    iosBundleId: 'com.example.shoeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQGheLE7B6UF3kcaOf161a7e3TpfUHYnE',
    appId: '1:581478733162:ios:23177416afcb72d3738113',
    messagingSenderId: '581478733162',
    projectId: 'shoe-shop-c265f',
    storageBucket: 'shoe-shop-c265f.firebasestorage.app',
    iosBundleId: 'com.example.shoeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDHYOgTeifdzwv1TDBcD6AlVh5UhVr-t8',
    appId: '1:581478733162:web:81a421a94794a2d7738113',
    messagingSenderId: '581478733162',
    projectId: 'shoe-shop-c265f',
    authDomain: 'shoe-shop-c265f.firebaseapp.com',
    storageBucket: 'shoe-shop-c265f.firebasestorage.app',
    measurementId: 'G-KH7NXGDD82',
  );
}
